#We will build mirror image of my app from base image 
FROM python

#set a working diroctires in docker.
WORKDIR /app

#Copy all other files into my docker

COPY . /app 
CMD ["python3","app.py"]
